const UI_PREFIX = 'xui-';

const SCROLL_EVENTBUS = `${UI_PREFIX}scroll-eventBus`;
const LAYOUT_EVENTBUS = `${UI_PREFIX}layout-eventBus`;
const FORM_EVENTBUS = `${UI_PREFIX}form-eventBus`;
const RADIOGROUP_EVENTBUS = `${UI_PREFIX}radioGroup-eventBus`;
const CHECKGROUP_EVENTBUS = `${UI_PREFIX}checkGroup-eventBus`;
const SELECT_EVENTBUS = `${UI_PREFIX}select-eventBus`;

const UPLOAD_SIZE_LIMIT = 1024 * 1024 * 2;

export {
  UI_PREFIX
  ,SCROLL_EVENTBUS
  ,LAYOUT_EVENTBUS
  ,FORM_EVENTBUS
  ,RADIOGROUP_EVENTBUS
  ,CHECKGROUP_EVENTBUS
  ,SELECT_EVENTBUS
  ,UPLOAD_SIZE_LIMIT
};
